apiVersion: v1
kind: Secret
metadata:
  name: meridian-api-prod
  namespace: prod
stringData:
  GEMINI_API_KEY: AIza24O2bKUU6Z5prHoYwmaVn57kZORN-EVtlem
  GEMINI_API_KEY_FALLBACK: AIzat2-dauU2WpNoWXuzeiPeKjNgA6BZ146h3L3
  JWT_SIGNING_SECRET: gn6J7Fug44u8JyuMxy586FugjRKi7SvGn3IbwhVTbGAgv8yL
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/XM4RYWIDN/L00TVLV2R/2viiH2XD2NVXd5loYGaZsLj8
